### ISSUE TITLE
tapping the 'event now on' button crashes the game and it doesn't open anymore

### ISSUE THREAD

**Issue by sansgeek** [RunnersRevival/revival_issues#11]
**Describe the bug**
tapping the 'event now on' button in the bottom right hand corner of the screen closed the game and no longer opens at all

**To Reproduce**

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J7
 - OS: Android 8.0 (Oreo)
 - Version: 2.2.0

**Additional context**

**Comment by sansgeek** [comment]
2 GB of free space on the dot

**Comment by sansgeek** [comment]
i got the in-game notification about the event and just pressed the button, i didn't know if there was an "event menu" or anything like that

**Comment by F121Live** [comment]
This is most likely due to Save Corruption and unrelated to the Events page, the reason the game crashes on startup is because the 'sfrn.game' and 'ifrn.game' files are 0 bytes.

I did, however, fix something related to the Event rewards window and this change will go live with the 2.2.1 update.
`[2.2.1] EventRewardsWindow no longer crashes MainMenu in Commit 88c58ce2369bb188ec341e3b37217812f2291a09`

Feel free to try with a fresh account, but I highly doubt it's replicable.
