### ISSUE TITLE
Won't install on Android 14/Oxygen OS 14

### ISSUE THREAD

**Issue by Airprince440788** [RunnersRevival/revival_issues#114]
I have:
- downloaded srr224.apk from the official website
- ran it through the default files app (has installed other apk files fine)
- i clicked install
- I get this error:
![Screenshot_2024-11-10-15-41-27-58_3d73e98b1ad3bd2575f7a56513d89a0c](https://github.com/user-attachments/assets/dc67b086-eaa4-4cb5-921d-289da06b7859)
Phone is 12/256gb OnePlus Nord 4

**Comment by JKouga** [comment]
Sonic Runners Revival version 2.2.4 is a 32-bit app.  Because certain devices no longer support 32-bit apps, 32-bit apps will not work with 64-bit only Android devices.  If this is the case, you will have to install the 2.3.0 beta to your device since that version supports 64-bit only Android devices.

**Comment by FairPlay137** [comment]
As mentioned by JKouga, Sonic Runners Revival 2.2.4 is a 32-bit app, which Android has dropped support for starting with Android 14 on many new devices. There is a notice about this on our website. In your case, the unstable build is the only one that will work for your device at this time. Closing as this isn't a proper bug report.
