### ISSUE TITLE
Character doesn’t move during the level

### ISSUE THREAD

**Issue by AppleSlayer1999** [RunnersRevival/revival_issues#36]
I was doing the story level and my character does not wanna move sometimes when I tap the screen he starts moving but there’s no model I can’t jump on the bugs or pick up items sometimes I pick up laser and he doesn’t move he just stays frozen 

![D2A66E11-3912-4D27-874A-B5D1D41472BD](https://user-images.githubusercontent.com/114631858/192919095-31602a4c-d4d5-411d-9aa8-0d4d98c3f486.png)
![D7C6D909-2844-4692-9F62-4B623FE6BA81](https://user-images.githubusercontent.com/114631858/192919121-31842c9c-49b9-4055-9f36-422bd4db21c5.png)
![A42757D7-356F-46A1-8C55-A020BFEABD4E](https://user-images.githubusercontent.com/114631858/192919129-77d39182-dbde-48b8-a406-816dd5db5fc0.png)
![C4CAE274-432C-4916-B4F3-2DB1C9BE9A75](https://user-images.githubusercontent.com/114631858/192919139-5e8a7242-d731-4921-9260-512b2d2dc942.png)

**Comment by SuperAj3** [comment]
Hi there,
In the future, please use the template provided for posting bugs, and share this information:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 14]
 - Version: [e.g. 2.2.0]

**Additional context**
Add any other context about the problem here.

**Comment by FairPlay137** [comment]
For those stumbling across this issue, and are somehow able to reproduce it, try clearing the cache thru the "Clear Cache" button on the title screen, since that usually resolves a lot of asset corruption issues that could lead to crashes and behavior similar or identical to what is seen here.
