### ISSUE TITLE
A few bugs I've encountered

### ISSUE THREAD

**Issue by PaperLeo** [RunnersRevival/revival_issues#54]
![Screenshot_20230217-212738](https://user-images.githubusercontent.com/125723678/219845949-f7cc08c9-4641-4496-a75b-0347df636935.png)
(1) There is something weird with the icons for each power-up as blue pixels appear next to them.

![Screenshot_20230217-213348](https://user-images.githubusercontent.com/125723678/219845970-d951b477-836b-4f72-bda9-ba10f39f630e.png)
(2)There's nothing wrong in this screenshot, but I wanted to point out as you jump through them to get to higher ground, there's an invisible wall on those floating platforms that very briefly stop you for a second before continuing with the run.

![Screenshot_20230217-213918](https://user-images.githubusercontent.com/125723678/219845986-abf7012f-ff30-48d8-b430-cdc2d334596c.png)
(3) When doing the story mode, there should be a total score counter from your run showing how much score is left.

![Screenshot_20230217-214123](https://user-images.githubusercontent.com/125723678/219846008-ca7aa8f4-163a-47a0-b03c-c786bb8ab28f.png)
(4) The portraits of the character should disappear completely when leaving (shown on right side of screenshot of Eggman's portrait).

**Comment by FairPlay137** [comment]
1. Those icons are supposed to have animations, but they don't due to an unfinished decompilation of the particular asset used in that part of the UI. We missed this in all previous versions from 2.1.0 all the way up to 2.2.3 due to the post-run level up feature not being figured out yet. This will be fixed in 2.3.0.
2. Weird quirk with the OG game. Not sure how feasible this would be to fix.
3. That's a pretty nice suggestion! We'll keep it in mind for future versions.
4. Again, this is a quirk with the OG game. We might fix it in the future, we might not. Regardless, this issue isn't planned for a fix at this time.

**Comment by FairPlay137** [comment]
Closing since some are invalid. If you want, you can split them into their own issues.
