### ISSUE TITLE
Is the roulette bugged

### ISSUE THREAD

**Issue by TheFlare01** [RunnersRevival/revival_issues#70]
**Describe the bug**
So, when you go to spin it's rng, but if you hit spin again, the arrow slows down so you can hit what you want every time (with slight practice)
**To Reproduce**
Ticket wheel
Spin
Spin again before it ends normally 
And it should slow down heavily

**Comment by JKouga** [comment]
This is what is known as a placebo.  Tapping simply just skips the animation, whether it would be in the Premium Roulette or in the Item Roulette.  Here is FairPlay137's explanation of how the Roulette worked:

"When you click the spin button, the game reaches out to the server to spin the wheel, and the game expects to hear back from the server in regards to what the spin landed on, as well as the updated player data.  AFAIK that's how it worked in every official version of Sonic Runners, including 1.0.x, 1.1.x, and 2.0.x. We haven't changed the roulette code for Revival other than the RNG-based reimplementation in our server."

Your bug report unfortunately will be marked as "Invalid" and "Won't Fix" due to FairPlay137's explanation.

**Comment by TheFlare01** [comment]
Ok, thanks. It was weird that when I did it I almost got jackpot 2 times, why I felt like it was a bug. But thanks for the information
